### PR TITLE
Cookie consent dashboard

### PR DESCRIPTION
**Pull request by BibianaC**
`site_id` pending.

### CODE REVIEW

**Comment by michaelwood** [comment]
Looks good so far - don't forget to remove <head> and <body> tags from the cookie template though

**Comment by BibianaC** [comment]
Thanks, @michaelwood. I didn't think about removing the tags.

**Comment by BibianaC** [comment]
@michaelwood I have now removed the tags.

**Comment by BibianaC** [comment]
`site_id` added.

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
