### PR TITLE
Mw/grants indi

### PR DESCRIPTION
**Pull request by michaelwood**

### CODE REVIEW

**Comment by michaelwood** [comment]
Adds headline stats that will look like:

image

Assigning to @mariongalley for visual review

**Comment by mariongalley** [comment]
Thanks @michaelwood - I've run this past Katherine and we're both happy with this design. Could you change the order of the stats to be:
- Row 1: Publishers, Funders, Grants
- Row 2: Orgs, Inds, Amount

**Comment by michaelwood** [comment]
> Thanks @michaelwood - I've run this past Katherine and we're both happy with this design. Could you change the order of the stats to be:
> 
> * Row 1: Publishers, Funders, Grants
> * Row 2: Orgs, Inds, Amount

Great. That's now done. 

Over to @codemacabre for code review.

**Review by codemacabre — DISMISSED** [review]
LGTM!

**Comment by michaelwood** [comment]
I missed off the commit to rebuild the vue-registry application so this is now added, also added a test for this. Can i get a re-review @codemacabre :)

**Review by codemacabre — APPROVED** [review]

**Pull request merged**
